subgraphs:
  users:
    routing_url: http://127.0.0.1:11800/graphql
    schema:
      subgraph_url: http://127.0.0.1:11800/graphql
  students:
    routing_url: http://127.0.0.1:11801/graphql
    schema:
      subgraph_url: http://127.0.0.1:11801/graphql
  faculties:
    routing_url: http://127.0.0.1:11802/graphql
    schema:
      subgraph_url: http://127.0.0.1:11802/graphql
